scheduling:
  initial-delay: 10000
  fixed-delay: 60000

altinn:
  base-url: https://test-api.data.altinn.no/v1
  ocp-apim-subscription-key:

maskinporten:
  token-endpoint:
  audience:
  scope:
  issuer:
  kid:
  private-key:

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus

spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: PLAINTEXT

logging:
  level:
    no.novari.ebevis: TRACE