scheduling:
  initial-delay: 10000
  fixed-delay: 7200000

altinn:
  base-url: https://api.data.altinn.no/v1
  ocp-apim-subscription-key:

maskinporten:
  token-endpoint:
  audience:
  scope:
  issuer:
  kid:
  private-key:

management:
  endpoints:
    web:
      exposure:
        include: health, shutdown, prometheus

spring:
  profiles:
    include:
      - kafka

logging:
  level:
    no.novari.ebevis: debug
    no.fintlabs.altinn.maskinporten: info
    org.apache.kafka.clients: warn
